name: build-angle-mac

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-mac:
    strategy:
      matrix:
        os: [macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Angle version
        id: angle-version
        run: |
          echo "ANGLE_COMMIT=$(cat deps/angle-commit.txt)" >> $GITHUB_OUTPUT
          ARCH=${{ runner.arch }}
          echo "LOWERCASE_ARCH=$(echo $ARCH | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Cache
        id: cache-angle
        uses: actions/cache@v3
        with:
          path: build/angle.out
          key: angle-${{ runner.os }}-${{ runner.arch }}-${{ steps.angle-version.outputs.ANGLE_COMMIT }}

      - name: Build Angle
        if: steps.cache-angle.outputs.cache-hit != 'true'
        run: |
          ./orcadev build-angle --release

      - uses: actions/upload-artifact@v4
        with:
          name: angle-mac-${{steps.angle-version.outputs.LOWERCASE_ARCH}}
          path: build/angle.out
