name: build-angle-win

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Angle version
        id: angle-version
        shell: cmd
        run: |
          @chcp 65001>nul
          set /p ANGLE_COMMIT=<deps/angle-commit.txt
          echo ANGLE_COMMIT=%ANGLE_COMMIT% >> %GITHUB_OUTPUT%

      - name: Cache
        id: cache-angle
        uses: actions/cache@v3
        with:
          path: build/angle.out
          key: angle-${{ runner.os }}-${{ runner.arch }}-${{ steps.angle-version.outputs.ANGLE_COMMIT }}

      - name: Build Angle
        if: steps.cache-angle.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          orcadev build-angle --release

      - uses: actions/upload-artifact@v4
        with:
          name: angle-windows-x64
          path: build/angle.out
